// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Contract struct {
	UserID       uuid.UUID
	CreatedAt    time.Time
	ContractID   string
	ContractName string
}

type Session struct {
	UserID    uuid.UUID
	CreatedAt time.Time
	TokenHash string
}

type User struct {
	UserID       uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Email        string
	PasswordHash string
}

type Wallet struct {
	UserID         uuid.UUID
	CreatedAt      time.Time
	WalletID       uuid.UUID
	WalletName     string
	WalletKeystore string
	WalletAddress  string
}
